setupQuiz({
  formSelector: "#finalQuiz",
  resultSelector: "#finalQuizResult",
  quizId: "final",
  showProgress: true,
  answers: {
    f1: "a",
    f2: "a",
    f3: "a",
    f4: "a",
    f5: "a",
    f6: "a",
    f7: "a",
    f8: "a",
    f9: ["reflection", "dispersion"],
    f10: ["5", "5.0"],
    f11: ["静止", "处于静止", "静止状态"],
    f12: ["total", "pour", "remain", "calc"],
    f13: {
      parallel: "focus",
      focus: "axis",
      center: "straight",
    },
    f14: ["bean-gap", "big-volume"],
    f15: ["myopia-front", "myopia-concave", "hyperopia-convex"],
    f16: ["b-start", "a-faster"],
    f17: "below",
    f18: ["below-boiling", "heat-more", "balance"],
    f19: ["10", "10.0"],
    f20: ["same-pitch", "different-timbre", "short-high"],
  },
  questionTypes: {
    f9: "multi",
    f10: "text",
    f11: "text",
    f12: "order",
    f13: "match",
    f14: "multi",
    f15: "multi",
    f16: "multi",
    f18: "multi",
    f19: "text",
    f20: "multi",
  },
  answerDetails: {
    f9: "判断方法：平面镜成像、白光色散都和光的传播有关；沸腾属于物态变化，回声属于声现象。",
    f10: "计算过程：v = s / t = 60 m ÷ 12 s = 5 m/s。",
    f11: "判断方法：s-t 图像水平表示路程不再增加，所以这一段静止。",
    f12: "实验逻辑：用总质量减剩余质量，得到倒入量筒那部分液体的质量，再除以量筒读出的体积。",
    f13: "作图口诀：平行过焦点，过焦点变平行，过光心不偏折。",
    f14: "判断方法：红豆空隙和量筒读数偏大都会让体积偏大，因此密度偏小。",
    f15: "判断方法：近视是像在视网膜前方，用凹透镜发散；远视是像在视网膜后方，用凸透镜会聚。",
    f16: "读图方法：纵轴表示距离参考点 O 的距离。A 在 0 到 5 s 内从 0 m 到 10 m，平均速度为 2 m/s；B 从 5 m 到 10 m，平均速度为 1 m/s，所以 A 的平均速度更大，B 不是从 O 出发。",
    f17: "判断方法：m-V 图像斜率表示密度；90% 酒精含水更少，密度比 75% 消毒液更小，所以图线应在甲线下方。",
    f18: "实验逻辑：升温时吸热大于散热；稳定在 95℃ 时吸热约等于散热，且没有达到通常条件下水的沸点，所以不沸腾。",
    f19: "判断方法：凸透镜成倒立等大实像时 u = v = 2f，所以 20 cm = 2f，f = 10 cm。",
    f20: "判断方法：同一个音说明音调相同；不同乐器发声体不同，音色不同；同种琴弦变短通常振动更快、音调更高。",
  },
  hints: {
    f1: "第 1 题回看第一章：判断运动和静止要先选参照物。",
    f2: "第 2 题回看第二章：声音传播需要介质。",
    f3: "第 3 题回看第三章：水蒸气直接变成霜是凝华。",
    f4: "第 4 题回看第四章：平面镜像和物到镜面的距离相等。",
    f5: "第 5 题回看第五章：凸透镜对平行光有会聚作用。",
    f6: "第 6 题回看第五章：近视眼通常用凹透镜矫正。",
    f7: "第 7 题回看第六章：密度公式是 ρ = m / V。",
    f8: "第 8 题回看第一章：速度公式中 t 表示时间。",
    f9: "第 9 题回看第四章：平面镜成像和白光色散属于光现象，沸腾是物态变化，回声是声现象。",
    f10: "第 10 题回看第一章速度计算：v = s / t = 60 m ÷ 12 s = 5 m/s。",
    f11: "第 11 题回看第一章 s-t 图像：水平线表示路程不变，所以这一段静止。",
    f12: "第 12 题回看第六章液体密度实验：先称总质量，再倒入量筒读体积，称剩余质量，最后计算。",
    f13: "第 13 题回看第五章透镜作图：平行过焦点、过焦点变平行、过光心不偏折。",
    f14: "第 14 题回看第六章误差方向：体积偏大或质量偏小会让密度偏小。",
    f15: "第 15 题回看第五章眼睛成像：近视像在前，用凹透镜；远视像在后，用凸透镜。",
    f16: "第 16 题回看第一章 s-t 图像：先读起点位置，再用距离变化量除以时间。",
    f17: "第 17 题回看第六章密度图像：m-V 图像越陡，密度越大。",
    f18: "第 18 题回看第三章沸腾条件：沸腾需要达到沸点并继续吸热。",
    f19: "第 19 题回看第五章成像规律：u = v = 2f 时成倒立等大的实像。",
    f20: "第 20 题回看第二章声音特性：音调看高低，音色看发声体特点，响度看振幅和距离等因素。",
  },
  reviewLinks: {
    f1: { href: "chapter1-motion.html#motion", label: "回看参照物" },
    f2: { href: "chapter2-sound.html#sound-origin", label: "回看声音传播" },
    f3: { href: "chapter3-states.html#state-change", label: "回看凝华" },
    f4: { href: "chapter4-light.html#reflection", label: "回看平面镜成像" },
    f5: { href: "chapter5-lenses.html#lens-basics", label: "回看凸透镜" },
    f6: { href: "chapter5-lenses.html#eyes-tools", label: "回看近视矫正" },
    f7: { href: "chapter6-density.html#density-formula", label: "回看密度公式" },
    f8: { href: "chapter1-motion.html#speed", label: "回看速度公式" },
    f9: { href: "chapter4-light.html#refraction", label: "回看光现象" },
    f10: { href: "chapter1-motion.html#speed", label: "回看速度计算" },
    f11: { href: "chapter1-motion.html#motion-graph", label: "回看 s-t 图像" },
    f12: { href: "chapter6-density.html#density-errors", label: "回看液体密度实验" },
    f13: { href: "chapter5-lenses.html#lens-practice", label: "回看透镜作图与投影仪调试" },
    f14: { href: "chapter6-density.html#density-errors", label: "回看误差方向" },
    f15: { href: "chapter5-lenses.html#eyes-tools", label: "回看近视和远视" },
    f16: { href: "chapter1-motion.html#motion-graph", label: "回看 s-t 图像" },
    f17: { href: "chapter6-density.html#density-formula", label: "回看密度图像" },
    f18: { href: "chapter3-states.html#boiling-exam", label: "回看沸腾条件" },
    f19: { href: "chapter5-lenses.html#image-rule", label: "回看凸透镜成像规律" },
    f20: { href: "chapter2-sound.html#sound-origin", label: "回看声音特性" },
  },
  badges: (score) => score >= 17 ? "上册预习非常稳" : score >= 14 ? "上册主线基本过关" : "建议按反馈回看章节",
  successMessage: "漂亮。你已经抓住八年级上册物理的主要线索，可以带着问题进入课堂。",
});
